name: "AI Code & PR Review"
description: "Perform code reviews and comment on diffs using OpenAI or Anthropic API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  AI_PROVIDER:
    description: "AI provider to use (openai or anthropic)."
    required: false
    default: "openai"
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: false
  OPENAI_API_MODEL:
    description: "OpenAI API model."
    required: false
    default: "o3-mini"
  ANTHROPIC_API_KEY:
    description: "Anthropic API key for Claude."
    required: false
  ANTHROPIC_API_MODEL:
    description: "Anthropic API model."
    required: false
    default: "claude-3-7-sonnet-20250219"
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
  ENABLE_SUMMARY:
    description: "Whether to generate a summary of all review findings"
    required: false
    default: "true"
  ENABLE_AUTO_FIX:
    description: "Whether to generate automated fixes for common issues"
    required: false
    default: "true"
  ENABLE_AUTO_PR:
    description: "Whether to automatically create a PR that applies all suggested fixes"
    required: false
    default: "false"
  SUGGESTION_STRATEGY:
    description: "How to prioritize suggestions: auto-fix-first, ai-first, or ai-only"
    required: false
    default: "auto-fix-first"
  REVIEW_FOCUS:
    description: "Areas to focus on during review, comma-separated (e.g., security,performance,bugs)"
    required: false
    default: ""
  CACHE_ENABLED:
    description: "Whether to use GitHub Actions cache for AI responses and comment history"
    required: false
    default: "true"
  CACHE_KEY_PREFIX:
    description: "Prefix for cache keys to avoid conflicts with other actions"
    required: false
    default: "ai-review-"
  CACHE_TTL_DAYS:
    description: "Number of days to keep cached data before expiring"
    required: false
    default: "7"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
